### ISSUE TITLE
java -jar MiraiCompose-windows-x64-1.0.0.jar报错

### ISSUE THREAD

**Issue by A-n-k-a** [sonder-joker/mirai-compose#61]
![image](https://user-images.githubusercontent.com/47747022/134703269-5c312f47-7240-4f2d-9659-972f63c4ada9.png)

您好，我想请问一下直接用Java运行报错如何解决
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:339)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:281)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:277)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:234)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:763)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1034)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:72)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:873)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:841)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:466)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:780)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:675)

**Comment by sonder-joker** [comment]
抱歉，目前不依赖java的版本有点问题，请使用自带java的版本也就是msi版本。未来会以改善。

**Comment by A-n-k-a** [comment]
好的，谢谢。
我可以保持这个issue开启，直到您改善为止吗？
