### ISSUE TITLE
一个个奇奇怪怪的问题

### ISSUE THREAD

**Issue by Agoines** [sonder-joker/mirai-compose#7]
```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at com.youngerhousea.miraicompose.ui.feature.MiraiComposeViewKt$MiraiComposeView$1.invoke(MiraiComposeView.kt:63)
	at com.youngerhousea.miraicompose.ui.feature.MiraiComposeViewKt$MiraiComposeView$1.invoke(MiraiComposeView.kt:47)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at com.youngerhousea.miraicompose.future.FutureKt$Application$1$1$1.invoke(Future.kt:31)
	at com.youngerhousea.miraicompose.future.FutureKt$Application$1$1$1.invoke(Future.kt:31)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:46)
	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:91)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2252)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2499)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:2625)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:724)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:100)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:437)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:411)
	at com.youngerhousea.miraicompose.future.ImmediateFrameClock.withFrameNanos(Future.kt:95)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invokeSuspend(Recomposer.kt:411)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invoke(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2.invoke(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$2.invokeSuspend(Recomposer.kt:639)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$2.invoke(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2$2.invoke(Recomposer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2.invokeSuspend(Recomposer.kt:638)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2.invoke(Recomposer.kt)
	at androidx.compose.runtime.Recomposer$recompositionRunner$2.invoke(Recomposer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at androidx.compose.runtime.Recomposer.recompositionRunner(Recomposer.kt:611)
	at androidx.compose.runtime.Recomposer.runRecomposeAndApplyChanges(Recomposer.kt:389)
	at androidx.compose.runtime.RecomposerKt$withRunningRecomposer$2$1.invokeSuspend(Recomposer.kt:63)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: Resource emptyIcon.png not found
	at com.youngerhousea.miraicompose.theme.ResourceImageKt.loadImageResource(ResourceImage.kt:36)
	at com.youngerhousea.miraicompose.theme.ResourceImage.<clinit>(ResourceImage.kt:15)
	... 50 more
```

**Comment by sonder-joker** [comment]
```
Caused by: java.lang.IllegalArgumentException: Resource emptyIcon.png not found
	at com.youngerhousea.miraicompose.theme.ResourceImageKt.loadImageResource(ResourceImage.kt:36)
	at com.youngerhousea.miraicompose.theme.ResourceImage.<clinit>(ResourceImage.kt:15)
	... 50 more
```
抱歉，忘了吧emptyIcon.png加到git里了
